name: pdp_ui8_facebook
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schuyler
  #     fonts:
  #       - asset: fonts/Schuyler-Regular.ttf
